### PR TITLE
Datatable Pagination bugxfix

### PR DESCRIPTION
**Pull request by Julien-Sytadelle**
Needed to remove the if (paginate) to make pagination work in Datatable.jsx

### CODE REVIEW

**Comment by ErikDakoda** [comment]
@Julien-Sytadelle I don't understand this change. The Datatable has to work both if the paginate prop is true and false. If you remove `if (paginate)` Datatable  breaks when paginate is false. Have you tried passing `paginate={true}` to your component?

**Comment by Julien-Sytadelle** [comment]
I had rowsPerPage undefined with the if block and paginate set to true.
Without the if block, it's working both for paginated and non paginated.
I just retested with the if block (I was behind master at time of coding) and it fails again.

**Comment by ErikDakoda** [comment]
Try the use case where you pass Datatable the data prop instead of having Datatable load the data. In that case if you remove `if (paginate)` then you'll get an error that paginationTerms is undefined.

**Comment by Julien-Sytadelle** [comment]
In the render variables declared in the if block need to exist. I will do something better.

**Comment by ErikDakoda** [comment]
Thank you @Julien-Sytadelle  :-)

**Comment by Julien-Sytadelle** [comment]
Ok, this work with data - no pagination and with collections paginated or not.

**Comment by ErikDakoda** [comment]
That appears to work. Thanks!

**Comment by Julien-Sytadelle** [comment]
You are welcome, totally forgot to test with data.

**Pull request merged**
